"""Update database from remote repo

Revision ID: 37348c638fee
Revises: 
Create Date: 2026-03-11 08:44:47.000756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37348c638fee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('vehicle_brand', sa.String(length=100), nullable=False),
    sa.Column('vehicle_model', sa.String(length=100), nullable=False),
    sa.Column('vehicle_year', sa.Integer(), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workshop_id', 'vehicle_plate', name='uq_workshop_vehicle_plate')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('workshop_client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('checkin_date', sa.DateTime(), nullable=False),
    sa.Column('estimated_finish_date', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('actual_hours', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('final_cost', sa.Float(), nullable=True),
    sa.Column('workshop_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workshop_client_id'], ['workshop_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('CLIENT', 'WORKSHOP', name='userrole'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('vehicles', 'plate',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_unique_constraint(None, 'vehicles', ['plate'])
    op.drop_constraint(op.f('workshops_user_id_key'), 'workshops', type_='unique')
    op.create_foreign_key(None, 'workshops', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workshops', type_='foreignkey')
    op.create_unique_constraint(op.f('workshops_user_id_key'), 'workshops', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.alter_column('vehicles', 'plate',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('CLIENT', 'WORKSHOP', name='userrole'),
               existing_nullable=False)
    op.drop_table('services')
    op.drop_table('workshop_clients')
    # ### end Alembic commands ###
