"""Create workshops table

Revision ID: 5669de9469e0
Revises: 66431ae25b33
Create Date: 2026-02-25 19:06:33.180579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5669de9469e0'
down_revision: Union[str, Sequence[str], None] = '66431ae25b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'plate',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_unique_constraint(None, 'vehicles', ['plate'])
    op.drop_constraint(op.f('workshops_user_id_key'), 'workshops', type_='unique')
    op.create_foreign_key(None, 'workshops', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workshops', type_='foreignkey')
    op.create_unique_constraint(op.f('workshops_user_id_key'), 'workshops', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.alter_column('vehicles', 'plate',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
