"""Update users table Vehicle relationship

Revision ID: 66431ae25b33
Revises: a793476e1b59
Create Date: 2026-01-29 09:12:42.931067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66431ae25b33'
down_revision: Union[str, Sequence[str], None] = 'a793476e1b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('vehicles_fk_user_fkey'), 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'users', ['user_id'], ['id'])
    op.drop_column('vehicles', 'fk_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('fk_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicles_fk_user_fkey'), 'vehicles', 'users', ['fk_user'], ['id'])
    op.drop_column('vehicles', 'user_id')
    # ### end Alembic commands ###
