"""create services_history table

Revision ID: 81977476ee57
Revises: aa3043742a82
Create Date: 2026-06-03 20:46:15.391551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81977476ee57'
down_revision: Union[str, Sequence[str], None] = 'aa3043742a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services_history', sa.Column('current_mileage', sa.Integer(), nullable=True))
    op.drop_column('services_history', 'mileage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services_history', sa.Column('mileage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('services_history', 'current_mileage')
    # ### end Alembic commands ###
