"""create services_history table

Revision ID: 89fceb537d51
Revises: be80440e36bd
Create Date: 2026-06-03 20:35:04.997141

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "89fceb537d51"
down_revision: Union[str, Sequence[str], None] = "be80440e36bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("services_history", sa.Column("tenant_id", sa.Uuid(), nullable=False))
    op.alter_column(
        "services_history",
        "service_type",
        existing_type=postgresql.ENUM(
            "OIL_CHANGE",
            "TIRE_ROTATION",
            "TIRE_REPLACEMENT",
            "BRAKE_SERVICE",
            "BATTERY_REPLACEMENT",
            "AIR_FILTER",
            "TRANSMISSION_SERVICE",
            "COOLANT_FLUSH",
            "BELT_REPLACEMENT",
            "INSPECTION",
            "OTHER",
            name="servicetype",
        ),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "services_history",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "services_history",
        "serviced_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "services_history",
        "next_service_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "services_history",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_services_history_vehicle_id"), table_name="services_history")
    op.create_index(
        op.f("ix_services_history_tenant_id"),
        "services_history",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_services_history_tenant_id_id",
        "services_history",
        ["tenant_id", "id"],
        unique=False,
    )
    op.create_index(
        "ix_services_history_tenant_id_vehicle_id",
        "services_history",
        ["tenant_id", "vehicle_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "services_history", "vehicles", ["vehicle_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "services_history", "tenants", ["tenant_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services_history", type_="foreignkey")
    op.drop_constraint(None, "services_history", type_="foreignkey")
    op.drop_index(
        "ix_services_history_tenant_id_vehicle_id", table_name="services_history"
    )
    op.drop_index("ix_services_history_tenant_id_id", table_name="services_history")
    op.drop_index(op.f("ix_services_history_tenant_id"), table_name="services_history")
    op.create_index(
        op.f("ix_services_history_vehicle_id"),
        "services_history",
        ["vehicle_id"],
        unique=False,
    )
    op.alter_column(
        "services_history",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "services_history",
        "next_service_date",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "services_history",
        "serviced_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "services_history",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "services_history",
        "service_type",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM(
            "OIL_CHANGE",
            "TIRE_ROTATION",
            "TIRE_REPLACEMENT",
            "BRAKE_SERVICE",
            "BATTERY_REPLACEMENT",
            "AIR_FILTER",
            "TRANSMISSION_SERVICE",
            "COOLANT_FLUSH",
            "BELT_REPLACEMENT",
            "INSPECTION",
            "OTHER",
            name="servicetype",
        ),
        existing_nullable=False,
    )
    op.drop_column("services_history", "tenant_id")
    # ### end Alembic commands ###
