"""Update users table Vehicle relationship

Revision ID: a793476e1b59
Revises: 0e9e9b09975d
Create Date: 2026-01-29 09:11:59.867180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a793476e1b59'
down_revision: Union[str, Sequence[str], None] = '0e9e9b09975d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('fk_user', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_vehicles_owner_id'), table_name='vehicles')
    op.create_foreign_key(None, 'vehicles', 'users', ['fk_user'], ['id'])
    op.drop_column('vehicles', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_index(op.f('ix_vehicles_owner_id'), 'vehicles', ['owner_id'], unique=False)
    op.drop_column('vehicles', 'fk_user')
    # ### end Alembic commands ###
