"""create services_history table

Revision ID: aa3043742a82
Revises: 89fceb537d51
Create Date: 2026-06-03 20:37:24.016809

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "aa3043742a82"
down_revision: str | Sequence[str] | None = "89fceb537d51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
