"""create services_history table

Revision ID: be80440e36bd
Revises: 0003_add_tenant_foundation
Create Date: 2026-06-03 20:24:18.003477

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be80440e36bd"
down_revision: str | Sequence[str] | None = "0003_add_tenant_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column(
            "service_type",
            sa.Enum(
                "OIL_CHANGE",
                "TIRE_ROTATION",
                "TIRE_REPLACEMENT",
                "BRAKE_SERVICE",
                "BATTERY_REPLACEMENT",
                "AIR_FILTER",
                "TRANSMISSION_SERVICE",
                "COOLANT_FLUSH",
                "BELT_REPLACEMENT",
                "INSPECTION",
                "OTHER",
                name="servicetype",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("mileage", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("serviced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_service_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_service_mileage", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_services_history_vehicle_id"),
        "services_history",
        ["vehicle_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_services_history_vehicle_id"), table_name="services_history")
    op.drop_table("services_history")
    # ### end Alembic commands ###
