"""Create workshops table

Revision ID: d088ce143de7
Revises: 5669de9469e0
Create Date: 2026-02-25 19:08:46.698435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd088ce143de7'
down_revision: Union[str, Sequence[str], None] = '5669de9469e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workshops_user_id_fkey'), 'workshops', type_='foreignkey')
    op.drop_column('workshops', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshops', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('workshops_user_id_fkey'), 'workshops', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
